version: '3.8'

services:
    migrate:
        image: migrate/migrate
        volumes:
            - ./migrations:/migrations
        command: ["-path", "/migrations", "-database", "postgres://postgres:qwerty@postgres:5432/anifox?sslmode=disable", "up"]
        depends_on:
            - postgres
    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: qwerty
            POSTGRES_DB: anifox
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
